
export const SET_NAV_HEIGHT = 'SET_NAV_HEIGHT'

export const REQUEST_MOBILE_LOGIN = 'REQUEST_MOBILE_LOGIN'
export const REQUEST_EMAIL_LOGIN = 'REQUEST_EMAIL_LOGIN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_PLAYER = 'SET_USER_PLAYER'
export const SET_USER_COMMENT_INFO = 'SET_USER_COMMENT_INFO'

export const REQUEST_LOGIN_STATUS = 'REQUEST_LOGIN_STATUS'
export const REQUEST_USER_DETAIL = 'REQUEST_USER_DETAIL'

