
export const REQUEST_MOBILE_LOGIN = 'REQUEST_MOBILE_LOGIN'
export const REQUEST_EMAIL_LOGIN = 'REQUEST_EMAIL_LOGIN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_PLAYLIST = 'SET_USER_PLAYLIST'
export const SET_USER_PLAY_SETTING = 'SET_USER_PLAY_SETTING'
export const SET_USER_SHUFFLE = 'SET_USER_SHUFFLE'

export const REQUEST_LOGIN_STATUS = 'REQUEST_LOGIN_STATUS'
export const REQUEST_USER_DETAIL = 'REQUEST_USER_DETAIL'

